### ISSUE TITLE
Add timeline support to mobile versions

### ISSUE THREAD

**Issue by msramalho** [bellingcat/ukraine-timemap#1]
# Add timeline support to mobile versions

Currently, the TimeMap is usable in a mobile device but the timeline at the bottom is hidden (see image below). 

We want to allow for the use of this timeline in mobile devices, the challenge being the screen width forcing the days in the timeline to be unusable. Perhaps we could have a tab/overlay which would be "toggleable" that would show/hide the timeline in a readable format that could even use the fullscreen size (maybe in a vertical version compared to the current desktop horizontal version)

### Current desktop timeline (not readable if it's directly show in mobile)
![image](https://user-images.githubusercontent.com/19508417/159241572-7e60aca4-1346-42aa-a07c-8d104c8c7e80.png)

### Current mobile view
![mobile view](https://user-images.githubusercontent.com/19508417/159241057-f2a94562-b868-4eab-b719-5c71041294e5.png)

**Comment by TheLester** [comment]
Is there any ongoing work for creating mobile apps (iOS/Android) with the map? I would contribute to it

**Comment by fspoettel** [comment]
I haven't seen any efforts in that direction. However, a stated goal is to make the web version more compatible with mobile browsers. There is ongoing work relating to that in https://github.com/bellingcat/ukraine-timemap/pull/58.

**Comment by msramalho** [comment]
closing this for now. We can reopen if the upstream comes up with a different approach.
