### ISSUE TITLE
keep final date in timeline dynamically

### ISSUE THREAD

**Issue by msramalho** [bellingcat/ukraine-timemap#15]
Currently when we build and deploy the timemap, the final date that loads up on the timeline is the date of the last build, this is because that configuration is coming from config.js (`store.app.timeline.range` config value).

We would like to refactor the app so that the final date is always today, and the initial date is a given number of days in the past, calculated from today.

This print is from 28th and since the last deploy was on the 24th, that's the max date we see in the timeline. 
![image](https://user-images.githubusercontent.com/19508417/160441470-0c58a9e4-cdfb-4672-ac54-7153cf452360.png)

**Comment by hgrsd** [comment]
@msramalho I'd like to work on this issue.

Do you envisage the "number of days in the past, calculated from today" to be a configurable value (perhaps with a default) in `config.js`?

**Comment by msramalho** [comment]
Hi @hgrsd thanks for the interest in this issue, it's one of the most impactful in the short term to avoid having to do quick releases.

I would prefer if this number of days in the past is configurable, yup. I imagine we might change it a bit depending on the stage of the conflict we are at. Also, the current way it works, with a fixed range should not be removed but rather made into an alternative (between static - aka currently - and dynamic - aka this issue).

Let me know of other questions you have

**Comment by hgrsd** [comment]
I've implemented a first approach in #17. 

Happy to take comments or make changes, but I thought it'd be easier to discuss the details with an open PR
