### ISSUE TITLE
Add filter-panel support to mobile versions #1

### ISSUE THREAD

**Issue by msramalho** [bellingcat/ukraine-timemap#2]
# Add filter-panel support to mobile versions
(This issue is similar to #1 )

Currently, the TimeMap is usable in a mobile device but the filter-panel at the bottom is hidden (see image below). 

We want to allow for the use of the filters in mobile devices, the challenge being the screen width forcing the filters to go outside the screen. Perhaps we could have a tab/overlay which would be "toggleable" that would show/hide the filters with an extra `Done` button to close and see the map with the filters. 

### Current desktop filters (they overflow if directly show in mobile)
![image](https://user-images.githubusercontent.com/19508417/159242090-aa527255-31b1-4cb4-8cb6-204e18bee0be.png)

### Current mobile view
![mobile view](https://user-images.githubusercontent.com/19508417/159241057-f2a94562-b868-4eab-b719-5c71041294e5.png)

**Comment by ben-palmer** [comment]
@msramalho - is there active development that you're aware of right now to support a mobile-friendly layout? I'm hoping to contribute to this project (I have relevant mobile experience) if possible- but don't want to overlap any ongoing work.

**Comment by msramalho** [comment]
Hi @ben-palmer the most recent efforts towards that are stalled but available at https://github.com/bellingcat/ukraine-timemap/pull/13 do let me know if you have your own ideas or want to take it from there.

**Comment by fspoettel** [comment]
@msramalho this is fixed now I think.
