### ISSUE TITLE
"Next" button overlaps the time zoom controls

### ISSUE THREAD

**Issue by gaearon** [bellingcat/ukraine-timemap#21]
See here:

<img width="366" alt="Screenshot 2022-04-03 at 21 41 49" src="https://user-images.githubusercontent.com/810438/161447743-be4d13c5-9bf2-411d-bc71-b984dd4264aa.png">

Is this something we'd like to fix?

**Comment by breezykermo** [comment]
Yes, this is something we'd like to fix. The reason for this is related to #1 and #2; the platform really only supports a limited screen resolution currently.

**Comment by fspoettel** [comment]
@msramalho this is fixed now I think.
