### ISSUE TITLE
Clusters are flickering on zoom in

### ISSUE THREAD

**Issue by mourner** [bellingcat/ukraine-timemap#27]
As a side note, thanks for all the hard work on this map! As a Ukrainian and also the creator of Leaflet (and other deps like Supercluster), I really appreciate what you're doing.

Environment
-----------

* Your version (in package.json) or git commit hash: the one currently deployed on Bellingcat (as of April 5)
* Your operating system and version: macOS, reproducible in all browsers

Steps to reproduce
-----------------------------

1. Zoom in the map.

Current Behavior
----------------

Clusters are flickering annoyingly:

https://user-images.githubusercontent.com/25395/161832992-087a9795-7fc0-47d5-8912-c86ecf8fbe6d.mov

Expected Behavior
-----------------

No flickering, everything's smooth.

**Comment by gaearon** [comment]
I’ll have a look now.

**Comment by gaearon** [comment]
I'm sorry, this is my mistake. Here is a fix. https://github.com/bellingcat/ukraine-timemap/pull/29
