### ISSUE TITLE
mouse drag reveals a rectangle around the previous view area

### ISSUE THREAD

**Issue by msramalho** [bellingcat/ukraine-timemap#32]
Need to find root cause of this rectangle appearing, it's pretty easy to replicate:
* open the timemap
* drag with the mouse and the black-bordered rectangle will appear

I believe this glitch was introduced in some of the recent PRs.

![image](https://user-images.githubusercontent.com/19508417/162039802-d06b35c8-f69b-4295-a8fb-5b9edf23b494.png)

**Comment by fspoettel** [comment]
I believe that you are seeing the default chrome `user agent styling` for an element with `:focus` which is added once you start dragging. The default sets an `outline` which is consistent with what your screenshot shows.

It might have been surfaced by the react upgrade. it should be possible to suppress this with css. I'll open a PR later. :)

**Comment by msramalho** [comment]
great insight, thanks!
