### ISSUE TITLE
Language switch design

### ISSUE THREAD

**Issue by wattroll** [bellingcat/ukraine-timemap#37]
Initial discussion here https://github.com/bellingcat/ukraine-timemap/pull/25#pullrequestreview-931983046. I will add a button to sidebar that opens a panel with language selection, but it would be very helpful if somebody contributed to the overall design.  

For the sidebar button it would be amazing to have a Cyrillic-Latin-flavoured icon like [this](https://competition.adesignaward.com/design.php?ID=22868), but with characters unique to Latin/[Ukrainian](https://en.wikipedia.org/wiki/Ukrainian_alphabet)/[Russian](https://en.wikipedia.org/wiki/Russian_alphabet) alphabets. There is a good range of possible combinations like `LЪҐ`, `SЭЄ`, `WЫЇ`.

For the language selection large touch-screen-friendly buttons with texts in respective languages would be ideal. The currently selected option needs to stand out as such, and hover/focus/active states need to be supported.

I would advice against using flags for a list of languages because [flags are not languages](http://www.flagsarenotlanguages.com/blog/why-flags-do-not-represent-language/). There is a great number of Russian-speaking people (or even peoples) who don't identify with the state symbols of Russia.

**Comment by aspoet** [comment]
![grafik](https://user-images.githubusercontent.com/9062668/162245559-beb73bdf-18c2-44fd-a70d-6f7aa7dd2214.png)

Would this work ? Characters can be easily exchanged.

**Comment by wattroll** [comment]
Yeah would totally work as a starter. I've checked http://www.languageicon.org/ and the license is clearly stated, so we can totally use it with or without modifications.

> three characters have to be scaled down too much to fit the "page" making it illegible

How about one big character on each of three visible pages? Just like on original icon, but with the rear white page having a character.

Of course only the top of that rear character would be visible, but if you put a beautifully serifed [`Ё`](https://en.wikipedia.org/wiki/Yo_(Cyrillic)) glyph in there it would be very easily recognizable for most Russian speakers. It's a great character with long history and some interesting properties. In my opinion it's a well fitting symbol for of the language.

**Comment by fspoettel** [comment]
`Ё` is visually similar to a lot of western characters which might make the icon difficult to grep on smaller sizes. German has `Ä`, `Ö`, `Ü` for instance.
What about `ф`, `ж` or lowercase `ё`? I think all of these could work from an iconography perspective.

**Comment by aspoet** [comment]
I have iterated through various configurations with rear characters and they are too complex to be used in an UI. those complex configurations fall apart in anything smaller than 128x128px. However using a common glyph works pretty well imho (see attached image) . Is there a more suitable glyph? 

![grafik](https://user-images.githubusercontent.com/9062668/162329639-8a977e5d-6170-4bc1-8e8d-0db59b016eaf.png)

**Comment by msramalho** [comment]
I think `ф` is preferable to `Ё` since this last one is Russian-specific and Ukrainian speakers would not identify with it, we would like to have both UKR and RUS translations.

@aspoet thanks for these useful contributions.

**Comment by wattroll** [comment]
> they are too complex to be used in an UI

That makes sense. Thanks for taking time to check it.

> I think ф is preferable to Ё since this last one is Russian-specific

Indeed. If we only have two characters, the Cyrillic one should be an element of both alphabets. 

> Is there a more suitable glyph?

`Ф` looks very good to me. If I was trying alternatives, I'd try to see how `Ж` looks, but I don't have a preference or reasons.

How about changing the Latin character on the second page to something that is not also a Cyrillic character, e.g. `W`?

**Comment by aspoet** [comment]
> How about changing the Latin character on the second page to something that is not also a Cyrillic character, e.g. W?

Great idea, was not aware of the ambiguity. Looks really good and holds up quite well at 24px size as well.

![grafik](https://user-images.githubusercontent.com/9062668/162524887-61a4c875-ef7d-48e8-ab34-fac54a080030.png)
