### ISSUE TITLE
Add a "satellite map" layer and a switcher button

### ISSUE THREAD

**Issue by loganwilliams** [bellingcat/ukraine-timemap#4]
Add an option to switch the basemap tiles to a satellite/aerial view from Mapbox tiles (Historic, not current imagery.)

This issue requires:

1. Creating a new component for a map switcher that changes the active map layers in Leaflet.

**Comment by breezykermo** [comment]
This would be a candidate for PR-ing upstream to the core timemap repo, also.

**Comment by hgrsd** [comment]
I'm happy to take a stab at this one. I'm thinking a simple component to switch that's overlaid on the map (provided the Mapbox token is present), which dispatches an action to change the `ui.tiles` state.

**Comment by hgrsd** [comment]
@loganwilliams I've opened #12 for this issue :-)
