### ISSUE TITLE
Idea: Beeswarm chart for the timeline

### ISSUE THREAD

**Issue by ilyabo** [bellingcat/ukraine-timemap#42]
What do you guys think about using something like this for the timeline to make it more informative?

Here I experimented a bit with the data exported from the app:
https://observablehq.com/@ilyabo/bellingcat-civilian-harm-in-ukraine-beeswarm-timeline

![image](https://user-images.githubusercontent.com/351828/162610709-0ac71e6f-5bc8-4571-ac63-0a23a0d4e763.png)

The circle size has no meaning right now, but could be used to highlight e.g.  the more important events.

**Comment by msramalho** [comment]
This looks cool, and it's a great use of the open-sourced data! 
I would be cautious when trying to port this to the timeline at this stage for 2 reasons:
1. the height will be a function of #events and #filters, which may create a broken experience - not sure if you'd have a suggestion there?
2. we are still considering including some other data filter that would add more than 1 line to the timeline, like in [this instance](https://blmprotests.forensic-architecture.org/)

In any case, I'd be open to have a toggle which allowed for more than one visualization type of the timeline, but I wonder if it will be easy to do while keeping performance and interaction we have at the moment.

**Comment by breezykermo** [comment]
I agree, this is very cool @ilyabo! I would welcome a feature like this in [the upstream](https://github.com/forensic-architecture/timemap) also, as either:
1. A feature toggle in `config.js`, allowing timemap instance administrators to set this as the timeline visualization as an alternative to the current default of events plotted with time on the X axis, and (optionally) separated by categories on the Y axis.
2. A general toggle somewhere in the UI, which converts dynamically between the default timeline and this idea (as @msramalho has suggested). This toggle could also be feature flagged through the process described in 1.

**Comment by msramalho** [comment]
closing for now
