### ISSUE TITLE
Idea: Update base styles for map

### ISSUE THREAD

**Issue by fspoettel** [bellingcat/ukraine-timemap#47]
Some ideas for our map after looking at #43. Feel free to close the issue if you don't think these are improvements.

You can copy these styles here if you want to try them:
 * [satellite](https://api.mapbox.com/styles/v1/fspoettel/cl1uvkyii000n14qt20g5ds7z.html?title=copy&access_token=pk.eyJ1IjoiZnNwb2V0dGVsIiwiYSI6ImNqamlndjQwODJ2dG8za252NjNwMXg4YTAifQ.nLyeP7SZfMfcCZkdjYqSzQ&zoomwheel=true&fresh=true#13/33.75001/-118.4106)
 * [monochrome](https://api.mapbox.com/styles/v1/fspoettel/cl1uvvh38000a14p655knmh9i.html?title=copy&access_token=pk.eyJ1IjoiZnNwb2V0dGVsIiwiYSI6ImNqamlndjQwODJ2dG8za252NjNwMXg4YTAifQ.nLyeP7SZfMfcCZkdjYqSzQ&zoomwheel=true&fresh=true#9/37.78/-122.4241)

### Use `satellite-streets` istd. of `satellite`

Having labels on the satellite map helps a great deal with identifying cities, regions and streets. Screenshot below is a custom mapbox style created from the `satellite streets` preset, no other adjustments.

I also used a lighter accent color to help with contrast with the dark satellite layer.

![image](https://user-images.githubusercontent.com/1682504/162779365-8aaa5342-6cb1-462a-ba77-a414779476eb.png)

### Use `monochrome` as default layer

Screenshot below is a custom mapbox style created from the `monchrome` light preset, no other adjustments. Labels and lines are a bit less constrasted in this style and help clusters stick out more.

![image](https://user-images.githubusercontent.com/1682504/162781679-ece7098d-864d-4fc1-8d72-360d422bb93a.png)

![image](https://user-images.githubusercontent.com/1682504/162782550-6ef576f9-a153-434e-b807-4aaca8d16930.png)

**Comment by msramalho** [comment]
Hey @fspoettel thanks for the suggestion, I have configured a new satellite style forked from yours and with some modifications. Let's leave the purple for now since it visually breaks the pattern that is already associated with the platform even if the contrast is not perfect in satellite.

**Comment by fspoettel** [comment]
nice, thanks!

**Comment by msramalho** [comment]
I noticed I introduced a bug and broke the toggle. I did a hotfix [here](https://github.com/bellingcat/ukraine-timemap/commit/e51ee26d98069ac33f028802262cf0799de9cbee) but this should be fixed properly in the next couple of days.
