### ISSUE TITLE
refactor hot-fix introduced in new satellite tiles

### ISSUE THREAD

**Issue by msramalho** [bellingcat/ukraine-timemap#49]
full thread in #47  but this commit did a hot fix for a bug where the satellite toggle was blocked [here](https://github.com/bellingcat/ukraine-timemap/commit/e51ee26d98069ac33f028802262cf0799de9cbee). The commit hardcoded a value, but the detection of satellite vs default map should be independent of the mapbox tiles id

**Comment by breezykermo** [comment]
An idea for a slightly-less-hacky fix; you could just check if the word "mapbox" is in the string via a regex? Would this bug that you identified affect the satellite overlay feature in the upstream at all, or is it specific to other changes you made after merging that feature?

**Comment by msmych** [comment]
Hi, please check this one https://github.com/bellingcat/ukraine-timemap/pull/52
