### ISSUE TITLE
Clean up mobile support features

### ISSUE THREAD

**Issue by loganwilliams** [bellingcat/ukraine-timemap#5]
I implemented mobile support very quickly over the weekend. This should be cleaned up a bit before we make the repository public.

**Comment by breezykermo** [comment]
@loganwilliams how capable is the mobile support? We'd love it as an upstream PR as well if you've tested it and it works.

**Comment by msramalho** [comment]
Currently you can test how the ukraine.bellingcat.com website looks on mobile and the functionality is limited:
* you cannot interact with the timeline (see events outside the preset date-time) - we do have #1 for that
* you cannot use filter/categories - we do have issue #2 for that
