### ISSUE TITLE
Conflicting peer dependencies- clean run of `npm install` is failing.

### ISSUE THREAD

**Issue by ben-p-commits** [bellingcat/ukraine-timemap#56]
Environment
-----------

* version: 0.1.0 - `master`
* running on Mac OS 12.4, M1 Hardware
* `npm -v ` -> `8.15.0`

Steps to reproduce (for bugs only)
-----------------------------

1. clean clone of master branch, no changes to source. `git status` is clean.
2. run `npm install` in top dir of repo
3. peer dependency conflict error 💥

(I have attached logs)

Current Behavior
----------------
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: react-device-detect@1.17.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.0.0" from the root project
npm ERR!   peer react@"^18.2.0" from react-dom@18.2.0
npm ERR!   node_modules/react-dom
npm ERR!     react-dom@"^18.0.0" from the root project
npm ERR!     peer react-dom@"^16.0.0-0 || ^17.0.0-0 || ^18.0.0-0" from react-portal@4.2.2
npm ERR!     node_modules/react-portal
npm ERR!       react-portal@"^4.2.0" from the root project
npm ERR!     2 more (react-twitter-embed, @testing-library/react)
npm ERR!   3 more (react-portal, react-twitter-embed, @testing-library/react)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@">= 0.14.0 < 18.0.0" from react-device-detect@1.17.0
npm ERR! node_modules/react-device-detect
npm ERR!   react-device-detect@"^1.6.2" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@">= 0.14.0 < 18.0.0" from react-device-detect@1.17.0
npm ERR!   node_modules/react-device-detect
npm ERR!     react-device-detect@"^1.6.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See ~/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!    ~/.npm/_logs/2022-08-12T21_59_45_584Z-debug-0.log
```

Expected Behavior
-----------------

Successful installation of dependencies without conflicting dependencies.
[eresolve-report.txt](https://github.com/bellingcat/ukraine-timemap/files/9330055/eresolve-report.txt)
[2022-08-12T21_59_45_584Z-debug-0.log](https://github.com/bellingcat/ukraine-timemap/files/9330059/2022-08-12T21_59_45_584Z-debug-0.log)

[eresolve-report.txt](https://github.com/bellingcat/ukraine-timemap/files/9330063/eresolve-report.txt)
[2022-08-12T21_59_45_584Z-debug-0.log](https://github.com/bellingcat/ukraine-timemap/files/9330065/2022-08-12T21_59_45_584Z-debug-0.log)

**Comment by ben-palmer** [comment]
<img width="630" alt="image" src="https://user-images.githubusercontent.com/5067237/184451349-182db9d4-c406-4215-a968-ded3e740bb79.png">

Tried downgrading to node v16.x.x per the note on the https://github.com/forensic-architecture/timemap readme.

Same issue.

**Comment by ben-palmer** [comment]
Issue seems 'resolved' when downgrading to `v14.20.0`- albeit with plenty of warnings. Will create a PR to note this in the readme of this repo.

**Comment by msramalho** [comment]
Thanks @ben-palmer indeed node v14 is the most tested one here.

**Comment by fspoettel** [comment]
@loganwilliams @msramalho I would like to do a related cleanup: the dependencies are a bit of a mess, a lot of things that should be devDeps are not. OK if I clean this up as well?
