### ISSUE TITLE
Replace webpack-based tooling with vite

### ISSUE THREAD

**Issue by fspoettel** [bellingcat/ukraine-timemap#66]
While fixing #65, I noticed that without a complex migration webpack 5, we are stuck on Node 16. I took this as motivation to try and migrate this repo to `vite` and manged to get to a working state at https://github.com/fspoettel/ukraine-timemap/pull/1.

Results of the migration:

 * gets rid of a large amount of config code in this repo
 * removes 1800 packages from the npm tree
 * reduces final bundle size by 100kb gzipped - this is a product of a few node libraries having been packaged accidentally previously.
 * development server is much faster.
 * tests are working again (moved them vitest to avoid duplicate config)
 * deprecated sass syntax has been removed 

If this is something you would be interested in, I'm happy to finish the PR. cc @breezykermo, maybe this is interesting for upstream. I'm not willing to do this work again any time soon though. ^^

**Comment by msramalho** [comment]
Wow, that's very promising. If the remaining work is something you can manage then please proceed :pray:
It'd be great not to be stuck on 16 and it would always require this level of massive changes, plus great having tests again and all the other improvements. 
Curious to hear from @breezykermo too.
