### ISSUE TITLE
Add full-screen button

### ISSUE THREAD

**Issue by loganwilliams** [bellingcat/ukraine-timemap#7]
This would allow the map to be maximized from within an iframe.

This button should not appear on mobile, probably.

**Comment by fspoettel** [comment]
I would be interested in implementing this.

If I understand this issue correctly, an implementation could leverage the [element.requestFullscreen() browser API](https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullScreen) in combination with the iframe `allowfullscreen` attribute on the iframe.

Would it make sense to add the button to the toolbar ui in your opinion?

![Screenshot 2022-03-21 at 19-38-33 Civilian Harm in-mh](https://user-images.githubusercontent.com/1682504/159341965-2a211270-d3c9-4977-8091-7007d8b5c5d8.png)

**Comment by msramalho** [comment]
Hi @fspoettel thanks for taking an interest in helping!

The logic that you described is indeed what we are looking for: iframe with `allowfullscreen` + `requestFullScreen()`.

As for the UI placement, I think that sidebar makes sense (especially if we are not allowing for fullscreen in mobile - the sidebar is not visible on mobile). The order might be questionable but I'd say that's the easiest part to change if needed.

**Comment by msramalho** [comment]
(@breezykermo in case you find this one useful and have other ideas about the UI placement)

**Comment by breezykermo** [comment]
Yes indeed, we'd greatly appreciate a PR to the upstream repo at https://github.com/forensic-architecture/timemap for this as well @fspoettel!

**Comment by loganwilliams** [comment]
Looks really great, merged and deployed. Thanks for this.
